#!/bin/sh

. "$(dirname $0)/realpath.sh"

ROOT_DIR="$(dirname $(realpath $0))/../"
CUR_DIR=$(pwd)
cd $ROOT_DIR

docker run --rm -u $(id -u) -v $(pwd)/wordpress/wp-content/uploads:/uploads -v $(pwd)/.mc:/.mc \
--network $(pwd | awk -F'/' '{print $NF}')_default \
minio/mc $@

cd $CUR_DIR
